# Generated by Django 3.0.6 on 2020-05-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200511_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
